# Generated by Django 4.2 on 2023-04-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QueSub', models.CharField(default='匿名用户', max_length=50, verbose_name='反馈人')),
                ('City', models.CharField(max_length=50, verbose_name='城市')),
                ('Title', models.TextField(verbose_name='标题')),
                ('Class', models.CharField(max_length=50, verbose_name='类型')),
                ('Time', models.DateTimeField(verbose_name='提交时间')),
                ('Content', models.TextField(verbose_name='内容')),
                ('RepTime', models.DateTimeField(verbose_name='回复时间')),
                ('RepDep', models.CharField(max_length=50, verbose_name='回复部门')),
                ('RepCon', models.TextField(verbose_name='回复内容')),
                ('URL', models.CharField(max_length=100, verbose_name='来源')),
                ('reading', models.IntegerField(default=0, verbose_name='阅读量')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='账号名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('root', models.SmallIntegerField(choices=[(1, '管理员'), (2, '普通用户')], verbose_name='身份')),
            ],
        ),
    ]
